### ISSUE TITLE
Sni

### ISSUE THREAD

**Issue by nickbetteridge** [robur-coop/unipi#22]
Having sni bound into the unipi would, I think, be quite useful - especially in device constrained environments. The domain names in the path could pull in the different trees from git and ```--hostname``` could specify the hostnames in a string ```"my-server.example1.com,my-server.example2.com"```.

Would this be an easy enhancement to implement?

**Comment by hannesm** [comment]
Sure, so what do you have in mind for the git repositories: should my-server.example1.com and my-server.example2.com both have their data in one git repo (under different directories), or in separate git repositories?

**Comment by nickbetteridge** [comment]
I guess having separate git repositories for different domains would cover both cases - also giving the owners of the domains more control.

**Comment by nickbetteridge** [comment]
Ah - separate repositories wouldn't cover both cases! - but I would have that separate repositories is the best choice

**Comment by hannesm** [comment]
So, it is not entirely clear to me how to move since the design space is pretty open:
- similar to GitHub, we could use any number of repositories, look at a specific branch, and eventually at "CNAME"
- we could as well require a triple (hostname, repo, (auth, trust-anchor)) for each name to serve
- a third option is to have a single repo, and at the top-level one directory per hostname

It very much depends on use cases, so maybe @nickbetteridge is the best to answer what the goal would be. The single repository single host has shown to be already pretty useful.

**Comment by nickbetteridge** [comment]
The single repository single host is very useful!

The use cases I can think of really boil down to different users using a https endpoint for a service on a node, with each user deploying different unikernels for various services such as proxying gateway protocols, data storage/recovery etc.

Option no. 2, with the triple, would be truly excellent.

**Comment by nickbetteridge** [comment]
Already superceded with the excellent tlstunnel - nothing to do here!
